### ISSUE TITLE
Reproduce the Anomaly Segmentation

### ISSUE THREAD

**Issue by haoz19** [leonnnop/GMMSeg#4]
Hello,

Thanks for your great work! You achieve such a great performance on anomaly segmentation benchmarks such as Road Anomaly and Fishyscapes. We want to compare our proposed method with yours, while without the config files, we are not sure we can achieve the same result as you reported in the paper.

Will you release the pre-trained model or could you give us some instructions about how to reproduce your result plz?

Many Thanks,
Hao

**Comment by xhh12381** [comment]
Hi, Did you get a reply? @haoz19

**Comment by haoz19** [comment]
Nope

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Adam ***@***.***>
发送时间: Monday, July 17, 2023 8:27:28 AM
收件人: leonnnop/GMMSeg ***@***.***>
抄送: Zhang, Hao ***@***.***>; Mention ***@***.***>
主题: Re: [leonnnop/GMMSeg] Reproduce the Anomaly Segmentation (Issue #4)


Hi, Did you get a reply? @haoz19<https://urldefense.com/v3/__https://github.com/haoz19__;!!DZ3fjg!5EYXhRTWv5jwJYm3oVLA1oRo5EVKoZVbqHP8Brk8jkrXJeR2Tds59gMS2WIHlQ67LcfwsCeAxF5OLCdbCjb8t-nLLqLn$>

―

**Comment by leonnnop** [comment]
Hi,

Thanks for your interests!

I have uploaded the configuration files for Cityscapes. Please give them a try, and I hope they will be helpful for your needs. 

Please feel free to reopen this thread if you have any further questions or need assistance.
