### ISSUE TITLE
TypeError: EncoderDecoder: SegformerGMMSegHead: __init__() got an unexpected keyword argument 'decoder_params'

### ISSUE THREAD

**Issue by GuanchengWan** [leonnnop/GMMSeg#6]
It may get wrong config when reproducing the paper

**Comment by leonnnop** [comment]
It seems that you may have missed a part of the base code in GMMSeg. Before adapting the core code to other projects, I recommend running the entire project to ensure its proper functioning.

If you plan to adapt GMMSeg to the latest version of MMSegmentation on your own, please consider adding the following line to the BaseDecodeHead class in the decode_head.py file:

https://github.com/leonnnop/GMMSeg/blob/da1a5187a1eaa889bb101a5ab8974f9d1c7f1349/mmseg/models/decode_heads/decode_head.py#L74

If you have any further questions or need assistance, please feel free to reopen this thread.
