### ISSUE TITLE
Will you release other model configs?

### ISSUE THREAD

**Issue by lxtGH** [leonnnop/GMMSeg#7]
Hi! It is an interesting idea using GMM for segmentation. However, will you release the configs of other models?

**Comment by leonnnop** [comment]
Hi,

Thanks for your interest!

I have uploaded the configuration files for both Cityscapes and ADE20K. Please give them a try, and I hope they will be helpful for your needs.

Please feel free to reopen this thread if you have any further questions or need assistance.
